""""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def find_sum(n):
    fib = [1,2]
    i = 1
    sum = 0

    while fib[i] < n:
        fib.append(fib[i] + fib[i-1])
        if fib[i] % 2 == 0:
            sum += fib[i]
        i += 1
    return sum

print(find_sum(4000000))